from enum import Enum
class ConversationState(Enum):
    WELCOME = "WELCOME"
    MAIN_MENU = "MAIN_MENU"
    ORDERING = "ORDERING"
    DRINK_OFFER = "DRINK_OFFER"
    DRINK_SELECTION = "DRINK_SELECTION"
    DESSERT_OFFER = "DESSERT_OFFER"
    DESSERT_SELECTION = "DESSERT_SELECTION"
    SUMMARY = "SUMMARY"
    CONFIRMATION = "CONFIRMATION"
    COMPLETED = "COMPLETED"
    ASK_PHONE= "ASK_PHONE"
    ASK_SIZE = "ASK_SIZE" 
    CHOOSE_MODE = "CHOOSE_MODE"
    SELECT_CATEGORY = "SELECT_CATEGORY"
    SELECT_PRODUCT_FROM_CATEGORY = "SELECT_PRODUCT_FROM_CATEGORY"
    ASK_ADD_MORE = "ASK_ADD_MORE"
    ASK_QUANTITY = "ASK_QUANTITY"
    REPEAT_ORDER = "repeat_order"
    
    
