from enum import Enum
class ConversationState(Enum):
    WELCOME = "WELCOME"
    MAIN_MENU = "MAIN_MENU"
    ORDERING = "ORDERING"
    DRINK_OFFER = "DRINK_OFFER"
    DRINK_SELECTION = "DRINK_SELECTION"
    DESSERT_OFFER = "DESSERT_OFFER"
    DESSERT_SELECTION = "DESSERT_SELECTION"
    SUMMARY = "SUMMARY"
    CONFIRMATION = "CONFIRMATION"
    COMPLETED = "COMPLETED"
